### ISSUE TITLE
report_energy call overhead

### ISSUE THREAD

**Issue by YiranXu** [nyu-cds/dov205_assignment3#5]
In nbody function, the report_energy is called twice in a for loop where the second call is to print result. 
![image](https://cloud.githubusercontent.com/assets/16722329/23098989/0657f8dc-f62a-11e6-9ded-fc6e9adc7ad4.png)
They can be combined as one call: 
![image](https://cloud.githubusercontent.com/assets/16722329/23098998/5869e6da-f62a-11e6-886e-dac2e7060354.png)

I tested it. The performance is improved a little.

**Comment by dataframing** [comment]
I'm not 100% sure we should be making this change. I agree that removing code will lead to a decrease in code runtime, and I also agree that it *seems* like a waste of a call, but this may be affecting our results.

I tested this suggestion locally and found that the difference between excluding and including the first call to `report_energy()` leads to a *minor* difference in output values. See my results below:

I first ran the original `nbody.py` script (with the initial `report_energy()`) and directed the output to `nbody-included.txt`, likewise for `nbody-excluded.txt`:

```bash
python nbody.py > nbody-included.txt
vim nbody.py # deleted line 136: `report_energy()`
python nbody.py > nbody-excluded.txt
```

then I used NumPy to see whether the output values were, indeed, different.

```python
def read_output_file(file_name: str) -> np.array:
    with open(file_name, "r") as f:
        file_contents = f.readlines()
    numpy_array = np.array([float(line.strip()) for line in file_contents])
    return numpy_array

included = read_output_file("nbody-included.txt")
excluded = read_output_file("nbody-excluded.txt")

np.allclose(included, excluded)       # True!
np.equal(included, excluded)          # False, False, False, ..., False
```

The difference is tiny – the largest difference is on the order of 1 * 10^-13, or 0.0000000000001 – but I don't have enough domain experience to know whether the N-body simulation might be affected by a change of that magnitude. When we're dealing with astronomical bodies, sometimes we hold a premium on precision versus minor differences in runtime.

At times like these, I might refer back to the original researcher and ask if a difference like that would make a difference (or, refer to @jarrah42).

---

Given that this is just an assignment, I'll go ahead and make the commit. Just something to think about, though, going forward.
